# Codecov configuration file

coverage:
  # Status checks that will appear in the Pull Request
status:
  project: true
  patch: true
  changes: true

# Allows Codecov to post a comment on the PR with a coverage summary.
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
