# This workflow proposes a version bump by creating a pull request.
# It analyzes commits since the last tag to determine the next version.

name: Propose Version Bump

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  propose-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # We need the full history to analyze commits
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Get current version
        id: current_version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      # This is a simplified step to determine the next version.
      # Tools like 'semantic-release' in 'dry-run' mode can do this more robustly.
      - name: Determine next version
        id: next_version
        run: |
          # Simple logic: if 'feat:' is in commits, it's MINOR, otherwise it's PATCH.
          # A real implementation would be more sophisticated.
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "")
          COMMITS_SINCE_TAG=$(git log ${LAST_TAG}..HEAD --pretty=format:%s)
          
          if [[ "$COMMITS_SINCE_TAG" == *"feat:"* ]]; then
            # MINOR increment (e.g., 1.2.3 -> 1.3.0)
            NEXT_VERSION=$(echo ${{ steps.current_version.outputs.version }} | awk -F. '{print $1"."$2+1".0"}')
          else
            # PATCH increment (e.g., 1.2.3 -> 1.2.4)
            NEXT_VERSION=$(echo ${{ steps.current_version.outputs.version }} | awk -F. '{print $1"."$2"."$3+1}')
          fi
          
          echo "Calculated next version: $NEXT_VERSION"
          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Update version in pom.xml
        run: mvn versions:set -DnewVersion=${{ steps.next_version.outputs.version }} -DgenerateBackupPoms=false

      - name: Create Release Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): propose version ${{ steps.next_version.outputs.version }}"
          title: "🚀 Release: Version ${{ steps.next_version.outputs.version }}"
          body: |
            This PR was automatically created to propose the next release.
            
            **Suggested Version:** `${{ steps.next_version.outputs.version }}`
            
            Please review the changes and merge to trigger the release workflow.
          branch: "release/v${{ steps.next_version.outputs.version }}"
